#!/usr/bin/env bash
# Configures an Ubuntu server to change localhost to 127.0.0.2 and facebook.com to 8.8.8.8

cp /etc/hosts ~/hosts.backup
grep -v "localhost" /etc/hosts | grep -v "facebook.com" > /tmp/hosts.tmp
echo "127.0.0.2 localhost" >> /tmp/hosts.tmp
echo "8.8.8.8 facebook.com" >> /tmp/hosts.tmp
cp /tmp/hosts.tmp /etc/hosts
rm /tmp/hosts.tmp
